version: '3'
# Debug version of ContinuITy
services:
  eureka:
    image: continuityproject/eureka
    hostname: eureka
    networks:
      - continuity-network
    ports:
      - '8761:8761'

  rabbitmq:
    image: rabbitmq:3.6.8-management
    hostname: rabbitmq
    networks:
      - continuity-network
    ports:
      - '5672:5672'
      - '15672:15672'

  orchestrator:
    image: continuityproject/orchestrator
    hostname: orchestrator
    networks:
      - continuity-network
    ports:
      - '8080:80'
      - '5000:5000'
    depends_on:
      - rabbitmq
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  idpa:
    image: continuityproject/idpa
    hostname: idpa
    networks:
      - continuity-network
    ports:
      - '8081:80'
      - '5001:5000'
    depends_on:
      - rabbitmq
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --storage.path=/storage

  wessbas:
    image: continuityproject/wessbas
    hostname: wessbas
    networks:
      - continuity-network
    ports:
      - '8082:80'
      - '5002:5000'
    depends_on:
      - rabbitmq
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  request-rates:
    image: continuityproject/request-rates
    hostname: request-rates
    networks:
      - continuity-network
    ports:
      - '8086:80'
      - '5006:5000'
    depends_on:
      - rabbitmq
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /bin/app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  jmeter:
    image: continuityproject/jmeter
    hostname: jmeter
    networks:
      - continuity-network
    ports:
      - '8083:80'
      - '5003:5000'
    depends_on:
      - rabbitmq
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /bin/app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  cobra:
    image: continuityproject/cobra
    hostname: cobra
    networks:
      - continuity-network
    ports:
      - '8084:80'
      - '5004:5000'
    depends_on:
      - rabbitmq
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  cobra-db:
    image: elasticsearch:7.3.2
    hostname: cobra-db
    networks:
      - continuity-network
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node

  clustinator:
    image: continuityproject/clustinator
    hostname: clustinator
    networks:
      - continuity-network
    ports:
      - '8088:80'
    depends_on:
      - rabbitmq

  forecastic:
    image: continuityproject/forecastic
    hostname: forecastic
    networks:
      - continuity-network
    ports:
      - '8087:80'
    environment:
      - ELASTIC=cobra-db
    depends_on:
      - eureka

networks:
  continuity-network:
    driver: bridge
