server:
  port: ${port:0}
spring:
  application:
    name: jmeter
  rabbitmq:
    host: localhost
    listener:
      simple:
        default-requeue-rejected: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.uri:http://localhost:8761/eureka}
  instance:
    statusPageUrlPath: /swagger-ui.html
    preferIpAddress: true
    metadataMap:
      produces: load-test, test-result
      requires-for-load-test: workload-model
      requires-for-test-result: load-test
endpoints:
  prometheus:
    enabled: true
  web:
    exposure:
      include=*

endpoint:
  metrics:
    enabled=true

metrics:
  export:
    prometheus:
      enabled=true
  

