server:
  port: ${port:0}
spring:
  application:
    name: wessbas
  rabbitmq:
    host: localhost
    listener:
      simple:
        default-requeue-rejected: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.uri:http://localhost:8761/eureka}
  instance:
    statusPageUrlPath: /swagger-ui.html
    preferIpAddress: true
    metadataMap:
      produces: behavior-model, workload-model
      requires-for-behavior-model: sessions
      requires-for-workload-model: behavior-model