---
# Please not that the "@type" property refers to a YAML node tag !<TYPE>
# (see http://yaml.org/spec/1.2/spec.html#id2784064)
# A YAML validator might not be able to handle this.
$schema: http://json-schema.org/draft-04/schema#
title: Application Model
type: object
additionalProperties: false
properties:
  id:
    type: string
  timestamp:
    type: string
    pattern: \d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-\d{3}\w* #yyyy-MM-dd'T'HH-mm-ss-SSSX
  endpoints:
    type: array
    items:
      oneOf:
      - $ref: '#/definitions/HttpEndpoint'
required:
- timestamp
definitions:
  HttpEndpoint:
    type: object
    additionalProperties: false
    properties:
      "@type":
        type: string
        enum:
        - http
        default: http
      id:
        type: string
      domain:
        type: string
      port:
        type: string
      path:
        type: string
      method:
        type: string
      encoding:
        type: string
        default: <no-encoding>
      headers:
        type: array
        items:
          type: string
      parameters:
        type: array
        items:
          $ref: '#/definitions/HttpParameter'
      protocol:
        type: string
    required:
    - "@type"
    - domain
    - port
    - path
    - method
    - protocol
  HttpParameter:
    type: object
    additionalProperties: false
    properties:
      id:
        type: string
      name:
        type: string
      parameter-type:
        type: string
        enum:
        - REQ_PARAM
        - BODY
        - URL_PART
        - HEADER
        - FORM
    required:
    - name
    - parameter-type